### PR TITLE
add additional parameters to config file

### PR DESCRIPTION
**Pull request by Mettbrot**
add the two filter options as parameters to the config file

### CODE REVIEW

**Comment by Mettbrot** [comment]
@helgeerbe do you rather want these PRs to target dev?

**Comment by helgeerbe** [comment]
Yes please. Dev is our staging branch.

**Comment by Mettbrot** [comment]
@helgeerbe done.

**Comment by Mettbrot** [comment]
I also moved the building of filters for the where clause to the model, so everything sits together. 

@helgeerbe 
I was able to test this today, so I consider this ready for merge.

**Pull request merged**
