### PR TITLE
Add touch and mouse control

### PR DESCRIPTION
**Pull request by glenvorel**
This PR adds touch and mouse control.

- Touch the **left half** of the screen (`a`): previous picture
- Touch the **right half** of the screen (`d`): next picture
- Touch near the **top of the screen**: open menu

Menu items are configurable, the existing options include:
- **Pause** (` `): pause/resume the playback
- **Display off** (`o`): turn off the display (when off, any input from the selected peripheral device will turn it back on)
- **Location on/off** (`l`): shows or hides location information
- **Exit** (`e`): exit PictureFrame
- **Power down** (`p`): power down the device

Menu items offer customization via config. The **label** of each button can be modified (e.g., localized to a different language) as well as its **keyboard shortcut**.
The business logic of each menu item is universal for all input types. More menu items can be created by subclassing  `IPMenuItem` and defining its `callback` method.

As not to interfere with clock that is also near the top of the screen, when the menu is shown, then clock is hidden.

In the touch mode, if not interacting with the menu for a specific amount of time (defined in config), it automatically disappears. Auto-hiding can be disabled (config). Menu can be manually hidden by touching the screen anywhere outside of the menu, too.

In the mouse mode, the menu remains shown for as long as the mouse pointer hovers it.

In the keyboard mode, the menu is not rendered.

Only one mode can be selected at a time - it is not possible to simultaneously enable keyboard and mouse, for example. The reason is technical. In the keyboard mode, in order for menu items to register keyboard strokes, the menu must be constantly `show`n. In order not to block the view, is is positioned out of view. This behavior is incompatible with mouse and touch.

As the older `interface_kbd` has been effectively replaced by `interface_peripherals`, it has been removed.

There is one change that affects the global playback behavior. Previously, when the playback was paused, it was not possible to navigate to previous or next picture. With this PR, manual navigation to previous or next picture is possible even when the playback is paused.

## Known issues:
- The picframe does not run as a service with keyboard input enabled (both touch and mouse do).
- I encountered wrong touch-to-position mapping on my hardware - RPi3B+, Waveshare 10.1inch HDMI LCD (E). The screen has a resolution of 1024x600 px. While the pointer follows very precisely touch in the desktop, and pi3d correctly detects the screen resolution (both `Display.width` and `Display.height`), it seems as if pi3d internally tried to translate the touch to coordinates assuming 4:3 screen ratio (that would be 1024x768). If I compensate for this inaccuracy on the y axis, the touch is detected precisely. I would like to ask for your feedback from different touchscreens and resolutions to see if this logic applies universally or not.

### CODE REVIEW

**Comment by helgeerbe** [comment]
Hi @glenvorel finally I've got pygame working on my m1 Mac now. But pi3d needs openegl together with the option `pygame=True`. Unfortunately openegl is not available (or at least I don't now how to install it on my m1 Mac).

@paddywwoof do you have an idea, if openegl is really required together with pygame?

**Comment by glenvorel** [comment]
I made a few minor changes, the main one being that each menu item invocation is now consistently logged.

**Comment by helgeerbe** [comment]
Hi @glenvorel, I gave up to get this running on MacOS. But I will test it on my spare raspberry pi3 on buster.

**Comment by helgeerbe** [comment]
@glenvorel  Hi I merged your code into release 2022.02.20 and mentioned you in the Acknowledgement chapter of Readme. If you would like to see your full name, please let me know. Hope it's fine, if I would be the maintainer of this code also in the future.

**Comment by glenvorel** [comment]
Hi @helgeerbe, as I wrote in the PR description, there are some known issues so it will almost definitely need some maintenance in the future. You can feel free to maintain the code. You can also ping me and I'll do my best to help.
Thank you for the mention in acknowledgments. My GitHub username is in fact my full name - Glen Vorel.

**Pull request merged**
